---
- name: Set timezone America/Sao_Paulo
  timezone:
    name: America/Sao_Paulo

- name: Add contrib non-free software
  copy:
    src: sources.list
    dest: /etc/apt/sources.list

- name: Add backports
  copy:
    src: bullseye-backports.list
    dest: /etc/apt/sources.list.d/bullseye-backports.list

- name: zfs pin
  copy:
    src: 90_zfs
    dest: /etc/apt/preferences.d/90_zfs

- name: Package | Install lists packages
  apt:
    name:
      - cargo
      - gnome-software-plugin-flatpak
      - openssh-server
      - snapd
      - flatpak
      - zsh
      - geary
      - bash-completion
      - openssh-server
      - vim
      - git
      - unar
      - htop
      - tree
      - dstat
      - screen
      - curl
      - wget
      - ccze
      - tmux
      - terminator
      - tig
      - unzip
      - neofetch
      - iotop
      - pciutils
      - usbutils
      - nmap
      - youtube-dl
      - squashfs-tools
      - shntool
      - unrar
      - p7zip
      - mc
      - nnn
      - sshfs
      - gnome-tweak-tool
      - qt5ct
      - chrome-gnome-shell
      - webp
      - pdf2djvu
      - poppler-utils
      - imagemagick
      - xclip
      - xsel
      - syncthing
      - syncthing-gtk
      - filezilla
      - openvpn
      - btrfs-compsize

      - gnome-shell-extension-appindicator
      - gnome-shell-extension-desktop-icons
      - gnome-shell-extension-dashtodock
      #- gnome-shell-extension-system-monitor-applet
      - gnome-shell-extension-top-icons-plus
      #- gnome-shell-extension-vertical-workspaces
      #- gnome-shell-extension-auto-move-windows
      #- gnome-shell-extension-panel-favorites
      #- gnome-shell-extension-pop-shell
      #- gnome-shell-extension-systemMonitor
      #- gnome-shell-extension-sound-output-device-chooser
      - dpkg-dev
      - linux-headers-generic
      - linux-image-generic
      - zfs-dkms
      - zfsutils-linux

    state: latest
    update_cache: yes

- name: Setup SSHD
  service: name=ssh state=started enabled=yes


- name: Install webp thumbnailer
  template:
    src: webp.thumbnailer
    dest: /usr/share/thumbnailers/
    owner: root
    group: root
    mode: '0644'

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
