---
- name: Install X11 libs
  apt:
    name:
      - libx11-dev
      - libxcursor-dev 
      - libxrandr-dev
      - libxinerama-dev
      - libxi-dev
      - libgl1-mesa-dev
      - g++
      - libsdl2-gfx-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libsdl2-dev
      - libxxf86vm-dev
      - intltool
      - libglib2.0-dev
      - libtool
      - fonts-firacode
      - fritzing
      - openscad
      - prusa-slicer
      - cura
      - sigrok-cli
      - pulseview
      - cargo
    state: present

- name: Install "Snap"
  apt: name=snapd state=latest 

- name: Enable "Snap"
  service: name=snapd state=started enabled=yes

#- name: Create "snap" symlink
#  file:
#    src:  /var/lib/snapd/snap
#    dest: /snap
#    owner: root
#    state: link

- name: Install "vscode" with option --classic
  snap:
    name: code
    classic: yes

- name: Install "insomnia" 
  snap:
    name: insomnia

- name: Install "postbird" 
  snap:
    name: postbird        

- name: Install "codeblocks"
  apt:
    name: codeblocks

- name: Install "android-studio"
  snap:
    name: android-studio
    classic: yes

- name: Install "anjuta"
  apt:
    name: anjuta

- name: Install "arduino"
  apt:
    name: arduino

- name: Install "micro"
  apt:
    name: micro

- name: Install DBeaver
  flatpak:
    name: io.dbeaver.DBeaverCommunity
    state: present

- name: Install "zeal"
  apt:
    name: zeal